print("     *\n", "   * *\n", "  *   *\n",  " *     *\n", "***   ***\n", "  *   *\n", "  *   *\n", "  *****\n")
print("     *\n" * 2, "   * *\n" * 2, "  *   *\n",  " *     *\n", "***   ***\n", "  *   *\n", "  *   *\n", "  *****\n")
print("       * \n", "     * *\n", "    ** **\n", "   **   **\n",  "  **     **\n", " ******   ******\n", "  **   **\n", "  **   **\n", "  **********\n")

print("        *        "*2)
print("       * *       "*2)
print("      *   *      "*2)
print("     *     *     "*2)
print("    *       *    "*2)
print("   *         *   "*2)
print("  *           *  "*2)
print(" *             * "*2)
print("******     ******"*2)
print("     *     *     "*2)
print("     *     *     "*2)
print("     *     *     "*2)
print("     *     *     "*2)
print("     *     *     "*2)
print("     *     *     "*2)
print("     *******     "*2)

print("        *")
print("       * *")
print("      *   *")
print("     *     *")
print("    *       *")
print("   *         *")
print("  *           *")
print(" *             *")
print("******     ******")
print("     *     *")
print("     *     *")
print("     *     *")
print("     *     *")
print("     *     *")
print("     *     *")
print("     *******")